# Generated by Django 4.0.4 on 2022-04-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField()),
                ('isAuthenticated', models.BooleanField(default=True)),
            ],
        ),
    ]
