# Generated by Django 4.0.4 on 2022-06-28 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pseudo', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('isAuthenticated', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('XOF', 'XOF'), ('USD', 'USD'), ('EUR', 'EUR')], default='CFA', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('F', 'Finalisée'), ('A', 'Annulé'), ('C', 'En cours'), ('I', 'Initial')], default='I', max_length=1)),
                ('sens', models.CharField(choices=[('A', 'Achat'), ('V', 'Vente')], max_length=1)),
                ('quantityType', models.CharField(choices=[('F', 'FIXED'), ('R', 'RANGE')], max_length=50)),
                ('quantityFixe', models.CharField(blank=True, max_length=21, null=True)),
                ('quantityMin', models.CharField(blank=True, max_length=21, null=True)),
                ('quantityMax', models.CharField(blank=True, max_length=21, null=True)),
                ('amountType', models.CharField(choices=[('F', 'FIXED'), ('R', 'RANGE')], max_length=50)),
                ('amountFixe', models.CharField(blank=True, max_length=21, null=True)),
                ('amountMin', models.CharField(blank=True, max_length=21, null=True)),
                ('amountMax', models.CharField(blank=True, max_length=21, null=True)),
                ('publicationDate', models.DateTimeField(auto_now_add=True)),
                ('marge', models.IntegerField()),
                ('provider', models.CharField(choices=[('WAVE', 'Wave'), ('OM', 'Orange Money'), ('FREE', 'Free Money')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('F', 'Finalisée'), ('A', 'Annulé'), ('C', 'En cours')], default='C', max_length=1)),
                ('steps', models.CharField(choices=[('1', 'step 1'), ('2', 'step 2'), ('3', 'step 3'), ('4', 'step 4'), ('5', 'step 5'), ('6', 'step 6'), ('7', 'step 7'), ('8', 'step 8'), ('9', 'step 9'), ('10', 'step 10'), ('11', 'step 11'), ('12', 'step 12'), ('13', 'step 13')], max_length=2)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ad')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WAVE', 'Wave'), ('OM', 'Orange Money'), ('FREE', 'Free Money')], max_length=15)),
                ('phone', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
