# Generated by Django 4.0.4 on 2022-07-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='tradeHash',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='trade',
            name='walletAdress',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='trade',
            name='steps',
            field=models.CharField(choices=[('1', 'step 1'), ('2', 'step 2'), ('3', 'step 3'), ('4', 'step 4'), ('5', 'step 5'), ('6', 'step 6'), ('7', 'step 7'), ('8', 'step 8'), ('9', 'step 9'), ('10', 'step 10'), ('11', 'step 11'), ('12', 'step 12'), ('13', 'step 13')], default='1', max_length=2),
        ),
    ]
