# Generated by Django 4.0.4 on 2022-06-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='numero',
            new_name='phone',
        ),
    ]
