# Generated by Django 4.0.4 on 2022-05-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creationDate',
        ),
    ]
