# Generated by Django 4.0.4 on 2022-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trade_tradehash_trade_walletadress_alter_trade_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='walletAdress',
            new_name='walletAddress',
        ),
    ]
