# Generated by Django 4.0.4 on 2022-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_alter_ad_amountfixe_alter_ad_amountmax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='amountType',
            field=models.CharField(choices=[('F', 'FIXED'), ('R', 'RANGE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='quantityType',
            field=models.CharField(choices=[('F', 'FIXED'), ('R', 'RANGE')], max_length=50),
        ),
    ]
