# Generated by Django 4.0.4 on 2022-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_walletadress_trade_walletaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('FCFA', 'FCFA'), ('USD', 'USD'), ('EUR', 'EUR')], default='FCFA', max_length=50),
        ),
    ]
