# Generated by Django 4.0.4 on 2022-04-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
