# Generated by Django 4.0.4 on 2022-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_alter_ad_amounttype_alter_ad_quantitytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('XOF', 'XOF'), ('USD', 'USD'), ('EUR', 'EUR')], default='CFA',
                                   max_length=50),
        ),
    ]
