# Generated by Django 4.0.4 on 2022-08-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='transactionId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='txId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
