# Generated by Django 4.0.4 on 2022-04-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(blank=True),
        ),
    ]
