# Generated by Django 4.0.4 on 2022-04-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_isauthenticated_alter_user_lastlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
