# Generated by Django 4.0.4 on 2022-08-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trade_transactionid_trade_txid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='buyerWalletAdress',
            field=models.CharField(default='', max_length=256),
        ),
    ]
