# Generated by Django 4.0.4 on 2022-05-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
