# Generated by Django 4.0.4 on 2022-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trade_buyerwalletadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.IntegerField(default=777023861),
            preserve_default=False,
        ),
    ]
