# Generated by Django 4.0.4 on 2023-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trade_stephash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stepHash',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
