# Generated by Django 4.0.4 on 2022-05-25 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterParty', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('sens', models.CharField(max_length=50)),
                ('quantityType', models.CharField(max_length=50)),
                ('quantityValue', models.IntegerField()),
                ('amountType', models.CharField(max_length=40)),
                ('amountValue', models.IntegerField()),
                ('publicationDate', models.DateTimeField()),
                ('margin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='USD', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingDate', models.DateTimeField()),
                ('steps', models.CharField(max_length=40)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ad')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
