# Generated by Django 4.0.4 on 2022-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ad_user_currency_trade_ad_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(default='CFA', max_length=50),
        ),
    ]
