# Generated by Django 4.0.4 on 2022-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('CFA', 'CFA'), ('USD', 'USD'), ('EUR', 'EUR')], default='CFA', max_length=50),
        ),
    ]
