# Generated by Django 4.0.4 on 2022-05-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_paymentmethod_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
