# Generated by Django 4.0.4 on 2022-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_paymentmethod_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('F', 'Finalisée'), ('A', 'Annulé'), ('C', 'En cours')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sens',
            field=models.CharField(choices=[('A', 'Achat'), ('V', 'Vente')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('F', 'Finalisée'), ('A', 'Annulé'), ('C', 'En cours'), ('I', 'Initial')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='steps',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13)], max_length=2),
        ),
    ]
