# Generated by Django 4.0.4 on 2022-05-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_trade_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='publicationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='startingDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
