# Generated by Django 4.0.4 on 2022-05-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_ad_publicationdate_alter_trade_startingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='amountValue',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='quantityValue',
        ),
        migrations.AddField(
            model_name='ad',
            name='amountFixe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='amountMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='amountMin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='marge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='quantityFixe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='quantityMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='quantityMin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='amountType',
            field=models.CharField(max_length=50),
        ),
    ]
